### ISSUE TITLE
Error: extend is not a function

### ISSUE THREAD

**Issue by f4z3k4s** [craftzdog/pouchdb-adapter-react-native-sqlite#3]
Hey!

First of all, thank you for this package. We've been updating it recently to 1.0.2 which is supposed to work with PouchDB version 6.2.0. However, I experienced this error :
![screenshot from 2017-06-12 14-10-54](https://user-images.githubusercontent.com/14790796/27033745-fba18b06-4f7a-11e7-9022-f4d676be0716.png)
This is an importing issue, I managed to solve it by replacing `var extend = PouchUtils.jsExtend` with `var extend = require('pouchdb-extend')` in `pouchdb-adapter-react-native-sqlite/lib/index.js` and running `npm install pouchdb-extend`. Obviously, this is not suitable for long-term, could you check if the mentioned versions above are working correctly together?
Thank you!

**Comment by craftzdog** [comment]
Oops, 1.0.2 is made by #2 and I hadn't tested with it, sorry!
I confirmed that `Object.assign` works well.
I'm going to roll it out, thanks!

**Comment by craftzdog** [comment]
1.0.3 is out!

**Comment by f4z3k4s** [comment]
Woow, superfast! Thank you man, keep up the good work. :+1:
